In [ ]:
# Creating a 2D Array in Python
# A. Nested Lists (Most Common)

matrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

print(matrix)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [2]:
# B. List Comprehension
# Useful for initializing with default values. 

rows, cols = 3,4
matrix = [[0 for _ in range(cols)] for _ in range(rows)]
print(matrix)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [7]:
# ⚠️ Common Mistake:

wrong_matrix = [[0] * 4] * 3  # ❌
# wrong_matrix[0][0] = 99
print(wrong_matrix)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [ ]:
# C. Using NumPy (For Numerical Operations)
# Benefits: Faster operations, slicing, matrix algebra.



import numpy as np
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
# Accessing Elements

print(matrix[1][2])  # Row 1, Col 2 → 6



6


In [10]:
print(matrix[0])     # [1, 2, 3]


[1 2 3]


In [12]:
# Column (via list comprehension):

col_0 = [row[0] for row in matrix]
print(col_0) 

[1, 4, 7]


In [15]:
# Iterating Over a 2D Array

for i in range(len(matrix)):          # rows
    for j in range(len(matrix[0])):   # columns
        print(matrix[j][i], end=" ")
    print()

1 4 7 
2 5 8 
3 6 9 


In [14]:
# Direct Row Iteration

for row in matrix:
    for val in row:
        print(val, end=" ")
    print()

1 2 3 
4 5 6 
7 8 9 


In [16]:
# Update a Value

matrix[1][2] = 99
print(matrix)
# [[1, 2, 3], [4, 5, 99], [7, 8, 9]]

[[ 1  2  3]
 [ 4  5 99]
 [ 7  8  9]]


In [17]:
# Sum of All Elements

total = sum(sum(row) for row in matrix)
print(total)

138


In [18]:
# Transpose of a Matrix

transpose = [[row[i] for row in matrix] for i in range(len(matrix[0]))]
print(transpose)
# [[1, 4, 7], [2, 5, 8], [3, 6, 9]]

[[1, 4, 7], [2, 5, 8], [3, 99, 9]]


In [19]:
# Search in 2D Array

target = 5
found = any(target in row for row in matrix)
print(found)  # True

True
